version: 2

jobs:
  build:
    working_directory: ~/repo
    docker:
       - image: hashicorp/terraform:0.12.3
    steps:
      - checkout
      - run:
          name: terraform plan and notify
          command: |
            echo "export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $BASH_ENV
            echo "export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $BASH_ENV
            terraform init
            terraform plan | .circleci/bin/tfnotify plan
