version: 2.1

executors:
  terraform:
    working_directory: ~/repo
    docker:
       - image: hashicorp/terraform:0.12.3

commands:
  setup_aws_credentials:
    steps:
      - run:
          name: setup aws credentials
          command: |
            echo "export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $BASH_ENV
            echo "export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $BASH_ENV

jobs:
  terraform-plan:
    executor: terraform
    steps:
      - checkout
      - setup_aws_credentials
      - run:
          name: terraform plan and notify
          command: |
            cd terraform
            terraform init
            terraform plan | ../.circleci/bin/tfnotify plan
      - save_cache:
          key: terraform-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo

  terraform-apply:
    executor: terraform
    steps:
      - restore_cache:
          key: terraform-{{ .Environment.CIRCLE_SHA1 }}
      - setup_aws_credentials
      - run:
          name: terraform apply
          command: |
            cd terraform
            terraform apply -auto-approve

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - terraform-plan
      - terraform-apply:
          requires:
            - terraform-plan
          filters:
            branches:
              only:
                - master
