apiVersion: v1
kind: Service
metadata:
  name: sample
spec:
  selector:
    app: sample
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    # nodePortとして指定できるのは30000-32767までで、それ以外でapplyすると以下のようなエラーが返る:
    # `The Service "sample" is invalid: spec.ports[0].nodePort: Invalid value: 20000: provided port is not in the valid range. The range of valid ports is 30000-32767`
    nodePort: 30000
